Feature/support viewpager2
mango-tech/PageIndicatorView pull request #1
Opened 2019-05-28 11:55 UTC by davidllorca

Main purpose of this development is to abstract whole scrolling logic and so allowing support to ViewPager2 Android component also.

2019-05-28 13:19 UTC, davidgarciaanton commented on pageindicatorview/src/main/java/com/rd/PageIndicatorView.java
> +    public void setViewPager(@Nullable ViewPager2 pager) {
Qué te parecería tener directamente un método que fuese `setViewPager(ViewPagerAttacher attacher)`, así el cada Attacher específico se crearía fuera, y también dejaría de necesitar ser _generic_

Y en el único sitio que seguiríamos teniendo `instanceof` para crear el AttacherCorrespondiente es en el `findViewPager` por si configuramos el pager por `id` en el _xml_

2019-05-28 13:48 UTC, ncampsh commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeActivity.java
>      @SuppressWarnings("ConstantConditions")
Lint me dice que esta línea ya no es necesaria...

2019-05-28 13:50 UTC, ncampsh commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeActivity.java
> +        }}
Supongo que el comentario de @davidgarciaanton venía por aquí.... Up to you si quieres aplicar la mejora :).

2019-05-28 13:53 UTC, ncampsh commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeActivity.java
> +
No va a pasar, però mejor poner un if/else por si acaso le llegan los dos extras. Aunque realmente lo mejor sería un único parámetro que pueda tener dos valores.

2019-05-28 13:55 UTC, davidllorca commented on pageindicatorview/src/main/java/com/rd/PageIndicatorView.java
> +    public void setViewPager(@Nullable ViewPager2 pager) {
- [ ] Eliminar Generics

2019-05-28 13:56 UTC, davidllorca commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeActivity.java
>      @SuppressWarnings("ConstantConditions")
- [ ] Eliminar código

2019-05-28 13:57 UTC, davidllorca commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeActivity.java
> +
- [ ] Set layout por defecto

2019-05-28 14:01 UTC, ncampsh requested changes

2019-05-28 14:01 UTC, ncampsh commented on sample/src/main/java/com/rd/pageindicatorview/home/HomeAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
Cuánto tiempo sin ver un ViewHolder! jaja

2019-05-28 14:56 UTC, ncampsh approved these changes

2019-05-29 05:46 UTC, davidgarciaanton approved these changes
Nice!

2019-05-30 15:17 UTC, jfuentesanaya approved these changes

2019-05-31 05:35 UTC, miriamdl approved these changes

2019-05-31 10:22 UTC, merged